<img src="./images/banner.png" width="800">

# Broadcasting in NumPy

Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be used in arithmetic operations. It enables you to perform operations between arrays of different sizes without the need for explicit looping or reshaping.


In simple terms, broadcasting is a set of rules that NumPy follows to perform arithmetic operations on arrays with different shapes. When you perform an operation between two arrays, NumPy compares their shapes element-wise. If the dimensions of the arrays are not equal, NumPy will try to stretch or duplicate the smaller array to match the shape of the larger array.


For example, let's consider adding a scalar value to a NumPy array:


In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
scalar = 10

In [4]:
arr + scalar

array([11, 12, 13])

In this case, NumPy will broadcast the scalar value `10` to match the shape of the array `arr`. The scalar value will be added to each element of the array, resulting in a new array `[11, 12, 13]`.


Broadcasting also works with arrays of different shapes, as long as they satisfy certain conditions. NumPy follows a set of rules to determine if broadcasting is possible between two arrays. These rules will be discussed in detail in the next section.


Broadcasting is essential in NumPy for several reasons:

1. **Efficiency**: Broadcasting allows you to perform operations on arrays without the need for explicit loops. This can lead to more concise and efficient code, especially when working with large arrays.

2. **Memory Conservation**: Broadcasting avoids the need to create intermediate arrays to store the results of operations. Instead, NumPy performs the operations element-wise, which conserves memory and reduces overhead.

3. **Readability**: Broadcasting can make your code more readable and easier to understand. It allows you to express operations between arrays of different shapes in a more intuitive and natural way.

4. **Vectorization**: Broadcasting is a key component of vectorization in NumPy. Vectorization refers to the process of replacing explicit loops with array operations, which can significantly speed up computations. Broadcasting enables vectorization by allowing operations between arrays of different shapes.


By leveraging broadcasting, you can write more efficient and expressive code when working with NumPy arrays. It simplifies the process of performing element-wise operations and reduces the need for manual reshaping or looping.


In the following sections, we will explore the rules of broadcasting, see examples of how broadcasting works in practice, and discuss its advantages and limitations.

## <a id='toc1_'></a>[Rules of Broadcasting](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [Rules of Broadcasting](#toc1_)    
  - [Rule 1: Matching Dimensions](#toc1_1_)    
  - [Rule 2: Stretching Scalar Values](#toc1_2_)    
  - [Rule 3: Stretching One-Dimensional Arrays](#toc1_3_)    
- [Examples of Broadcasting](#toc2_)    
  - [Scalar and Array Broadcasting](#toc2_1_)    
  - [One-Dimensional Array Broadcasting](#toc2_2_)    
  - [Multi-Dimensional Array Broadcasting](#toc2_3_)    
  - [Broadcasting with Multiple Arrays](#toc2_4_)    
- [Advantages of Broadcasting](#toc3_)    
  - [Memory Efficiency](#toc3_1_)    
  - [Concise and Readable Code](#toc3_2_)    
- [Limitations and Pitfalls of Broadcasting](#toc4_)    
  - [Incompatible Array Shapes](#toc4_1_)    
  - [Unintended Consequences](#toc4_2_)    
- [Conclusion](#toc5_)    
- [Practice Exercise: Broadcasting in NumPy](#toc6_)    
  - [Solution](#toc6_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

NumPy follows a set of rules to determine if broadcasting is possible between two arrays. These rules define how arrays with different shapes can be used in arithmetic operations. Let's explore each rule in detail.


### <a id='toc1_1_'></a>[Rule 1: Matching Dimensions](#toc0_)


The first rule of broadcasting states that if the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.


For example, consider an array `A` with shape `(3, 4)` and an array `B` with shape `(4,)`:


```python
A.shape = (3, 4)
B.shape = (4,)
```

To perform an operation between `A` and `B`, NumPy will pad the shape of `B` with a leading dimension of size 1:


```python
B.shape = (1, 4)
```


After padding, the shapes of `A` and `B` are compatible for broadcasting.


### <a id='toc1_2_'></a>[Rule 2: Stretching Scalar Values](#toc0_)


The second rule of broadcasting states that if one of the arrays has a dimension size of 1, it can be stretched to match the size of the corresponding dimension in the other array.


Let's consider an example where we have an array `A` with shape `(3, 4)` and a scalar value `s`:


```python
A.shape = (3, 4)
s = 10
```


When performing an operation between `A` and `s`, NumPy will stretch the scalar value `s` to match the shape of `A`. The scalar value will be broadcasted to all elements of `A`.


Mathematically, this can be represented as:

$A_{ij} = A_{ij} + s$


where $i$ ranges from 0 to 2 and $j$ ranges from 0 to 3.


### <a id='toc1_3_'></a>[Rule 3: Stretching One-Dimensional Arrays](#toc0_)


The third rule of broadcasting states that if the arrays have the same number of dimensions and the size of any dimension is 1, that dimension can be stretched to match the size of the corresponding dimension in the other array.


Consider an example where we have an array `A` with shape `(3, 4)` and an array `B` with shape `(3, 1)`:


```python
A.shape = (3, 4)
B.shape = (3, 1)
```


When performing an operation between `A` and `B`, NumPy will stretch the second dimension of `B` to match the size of the second dimension of `A`.


Mathematically, this can be represented as:

$C_{ij} = A_{ij} + B_{i}$


where $i$ ranges from 0 to 2 and $j$ ranges from 0 to 3.


It's important to note that for broadcasting to work, the dimensions with size 1 must be compatible. If the arrays have different shapes and the dimensions with size 1 are not compatible, NumPy will raise a `ValueError`.


These rules allow NumPy to perform broadcasting between arrays of different shapes, enabling efficient and concise operations. By understanding and leveraging these rules, you can write more expressive and readable code when working with arrays of different sizes.


## <a id='toc2_'></a>[Examples of Broadcasting](#toc0_)

Now that we have a clear understanding of the rules of broadcasting, let's explore some practical examples to see how broadcasting works in NumPy.


### <a id='toc2_1_'></a>[Scalar and Array Broadcasting](#toc0_)


One of the most common examples of broadcasting is when performing operations between a scalar value and an array. Let's consider an example:


In [9]:
arr = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [7]:
scalar = 10

In [8]:
arr + scalar

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In this example, we have a 2-dimensional array `arr` and a scalar value `scalar`. When we perform the addition operation `arr + scalar`, NumPy broadcasts the scalar value to match the shape of `arr`. The scalar value is added to each element of the array.


The resulting array `result` will have the same shape as `arr`, and each element will be the sum of the corresponding element in `arr` and the scalar value:


```python
result = [[11, 12, 13],
          [14, 15, 16],
          [17, 18, 19]]
```


### <a id='toc2_2_'></a>[One-Dimensional Array Broadcasting](#toc0_)


Broadcasting also works with one-dimensional arrays. Let's consider an example where we have a 2-dimensional array and a 1-dimensional array:


In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [11]:
one_dim_arr = np.array([10, 20, 30])

In [12]:
arr + one_dim_arr

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In this case, `arr` has a shape of `(3, 3)`, and `one_dim_arr` has a shape of `(3,)`. According to the rules of broadcasting, NumPy will stretch `one_dim_arr` to match the shape of `arr`.


The resulting array `result` will have the same shape as `arr`, and each element will be the sum of the corresponding elements in `arr` and `one_dim_arr`:


```python
result = [[11, 22, 33],
          [14, 25, 36],
          [17, 28, 39]]
```


### <a id='toc2_3_'></a>[Multi-Dimensional Array Broadcasting](#toc0_)


Broadcasting also works with multi-dimensional arrays of different shapes, as long as they satisfy the rules of broadcasting. Let's consider an example:


In [13]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2 = np.array([
    [10],
    [20]
])

In [14]:
arr1 + arr2

array([[11, 12, 13],
       [24, 25, 26]])

In this example, `arr1` has a shape of `(2, 3)`, and `arr2` has a shape of `(2, 1)`. According to the rules of broadcasting, NumPy will stretch the second dimension of `arr2` to match the size of the second dimension of `arr1`.


The resulting array `result` will have the same shape as `arr1`, and each element will be the sum of the corresponding elements in `arr1` and `arr2`:


```python
result = [[11, 12, 13],
          [24, 25, 26]]
```


These examples demonstrate how broadcasting works in various scenarios, allowing you to perform operations between arrays of different shapes efficiently.


It's important to note that broadcasting is not limited to addition operations. It works with other arithmetic operations like subtraction, multiplication, and division as well.


### <a id='toc2_4_'></a>[Broadcasting with Multiple Arrays](#toc0_)

Broadcasting is not limited to operations between two arrays. NumPy allows broadcasting with multiple arrays as long as they satisfy the broadcasting rules.


Consider an example where we have three arrays of different shapes:


In [30]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10],
                 [20]])

arr3 = np.array([100, 200, 300])

In [31]:
arr1 + arr2 + arr3

array([[111, 212, 313],
       [124, 225, 326]])

In this case, `arr1` has a shape of `(2, 3)`, `arr2` has a shape of `(2, 1)`, and `arr3` has a shape of `(3,)`. NumPy will apply the broadcasting rules to make the shapes compatible for the addition operation.

1. `arr2` will be stretched along the second dimension to match the shape of `arr1`, resulting in a shape of `(2, 3)`.
2. `arr3` will be stretched along the first dimension to match the shape of `arr1`, resulting in a shape of `(2, 3)`.


After broadcasting, the arrays will have the same shape `(2, 3)`, and the element-wise addition will be performed:


```python
result = [[111, 212, 313],
          [124, 225, 326]]
```


Broadcasting with multiple arrays allows you to perform complex operations involving arrays of different shapes efficiently. It eliminates the need for manual reshaping and enables concise and readable code.


By leveraging broadcasting, you can write concise and efficient code when working with arrays of different shapes, eliminating the need for explicit loops or manual reshaping.

## <a id='toc3_'></a>[Advantages of Broadcasting](#toc0_)

Broadcasting in NumPy offers several advantages that make it a powerful and efficient technique for performing operations on arrays of different shapes. Let's explore two key advantages of broadcasting: memory efficiency and concise and readable code.


### <a id='toc3_1_'></a>[Memory Efficiency](#toc0_)


One of the primary advantages of broadcasting is its memory efficiency. When performing operations on arrays of different shapes, broadcasting eliminates the need to create intermediate arrays to store the results of the operations.


Consider an example where we want to add a scalar value to each element of an array:


In [15]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [16]:
scalar = 10

In [18]:
arr + scalar

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

Without broadcasting, we would need to create a new array with the same shape as `arr` and fill it with the scalar value before performing the addition. This would require additional memory to store the intermediate array.


However, with broadcasting, NumPy performs the addition operation element-wise, without creating any intermediate arrays. The scalar value is broadcasted to match the shape of `arr`, and the addition is performed in-place.


This memory efficiency becomes particularly important when working with large arrays or when performing multiple operations on arrays. By avoiding the creation of intermediate arrays, broadcasting reduces memory usage and improves the overall performance of the code.


### <a id='toc3_2_'></a>[Concise and Readable Code](#toc0_)


Another advantage of broadcasting is that it allows you to write concise and readable code. Broadcasting eliminates the need for explicit loops or manual reshaping of arrays, resulting in code that is easier to understand and maintain.


Let's consider an example where we want to multiply each row of a 2-dimensional array by a 1-dimensional array:


In [19]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [20]:
multiplier = np.array([10, 20, 30])
multiplier

array([10, 20, 30])

In [21]:
arr * multiplier

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

Without broadcasting, we would need to use explicit loops to multiply each element of `arr` by the corresponding element of `multiplier`:


In [23]:
result = np.zeros_like(arr)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        result[i, j] = arr[i, j] * multiplier[j]

result

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

This code is more verbose and harder to read compared to the broadcasting approach. With broadcasting, we can achieve the same result in a single line of code:


```python
result = arr * multiplier
```


Broadcasting allows us to express the operation in a more intuitive and readable way, without the need for explicit loops.


The concise and readable code provided by broadcasting makes it easier to understand the intent of the operation and reduces the chances of introducing errors. It also improves code maintainability, as the broadcasting approach is more expressive and self-explanatory.


In summary, broadcasting offers memory efficiency and concise and readable code, making it a valuable technique in NumPy. By leveraging broadcasting, you can write efficient and expressive code when working with arrays of different shapes, leading to improved performance and code clarity.

## <a id='toc4_'></a>[Limitations and Pitfalls of Broadcasting](#toc0_)

While broadcasting is a powerful and convenient feature in NumPy, it's important to be aware of its limitations and potential pitfalls. Let's discuss two common issues: incompatible array shapes and unintended consequences.


### <a id='toc4_1_'></a>[Incompatible Array Shapes](#toc0_)


One limitation of broadcasting is that it only works when the arrays have compatible shapes. NumPy follows specific rules to determine if broadcasting is possible between two arrays. If the shapes of the arrays do not satisfy these rules, NumPy will raise a `ValueError`.


Consider an example where we have two arrays with incompatible shapes:


In [24]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20],
                 [30, 40]])

In [25]:
result = arr1 + arr2  # Raises ValueError: operands could not be broadcast together with shapes (2,3) (2,2)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In this case, `arr1` has a shape of `(2, 3)`, and `arr2` has a shape of `(2, 2)`. These shapes are incompatible for broadcasting because the second dimension of `arr1` (size 3) does not match the second dimension of `arr2` (size 2), and neither of them is 1.


When you encounter a `ValueError` due to incompatible array shapes, it indicates that the arrays cannot be broadcasted together. To resolve this issue, you need to ensure that the shapes of the arrays satisfy the broadcasting rules. This may require reshaping one or both arrays using techniques like `reshape()`, `expand_dims()`, or `squeeze()`.


### <a id='toc4_2_'></a>[Unintended Consequences](#toc0_)


Another pitfall of broadcasting is the possibility of unintended consequences when performing operations on arrays with different shapes. Broadcasting can sometimes lead to unexpected results if not used carefully.


Let's consider an example where we have a 2-dimensional array and a 1-dimensional array:


In [27]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [28]:
one_dim_arr = np.array([10, 20, 30])

In [29]:
arr + one_dim_arr

array([[11, 22, 33],
       [14, 25, 36]])

In this case, `arr` has a shape of `(2, 3)`, and `one_dim_arr` has a shape of `(3,)`. According to the rules of broadcasting, NumPy will stretch `one_dim_arr` to match the shape of `arr` along the second dimension.


The resulting array `result` will have the same shape as `arr`, and each element will be the sum of the corresponding elements in `arr` and `one_dim_arr`:

```python
result = [[11, 22, 33],
          [14, 25, 36]]
```


While this result may be what you intended, it's important to be cautious when broadcasting arrays with different shapes. If the arrays have compatible shapes but the operation doesn't align with your expected outcome, it can lead to subtle bugs or incorrect results.


To avoid unintended consequences, it's crucial to carefully consider the shapes of the arrays and ensure that the broadcasting behavior aligns with your intended operation. It's also a good practice to add comments or assertions to clarify the expected shapes and the purpose of the broadcasting operation.


In summary, broadcasting has limitations when dealing with incompatible array shapes, and it can lead to unintended consequences if not used carefully. By understanding these limitations and being mindful of the potential pitfalls, you can effectively leverage broadcasting in your NumPy code while avoiding common issues.

## <a id='toc5_'></a>[Conclusion](#toc0_)

In this lecture, we have explored the concept of broadcasting in NumPy, a powerful feature that allows arrays with different shapes to be used in arithmetic operations efficiently.


Let's recap the key points we covered in this lecture:

1. Broadcasting is a set of rules that NumPy follows to perform arithmetic operations on arrays with different shapes.
2. The rules of broadcasting include:
   - If the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.
   - If the size of any dimension is 1, that dimension can be stretched to match the size of the corresponding dimension in the other array.
   - If the arrays have the same number of dimensions and the size of any dimension is not equal, that dimension must be 1 in one of the arrays.
3. Broadcasting enables efficient memory usage by avoiding the creation of intermediate arrays and allows for concise and readable code.
4. Examples of broadcasting include scalar and array broadcasting, one-dimensional array broadcasting, and multi-dimensional array broadcasting.
5. Broadcasting offers advantages such as memory efficiency and concise code, but it also has limitations when dealing with incompatible array shapes and can lead to unintended consequences if not used carefully.
6. Advanced broadcasting techniques, such as broadcasting with multiple arrays and broadcasting in user-defined functions, provide further flexibility and reusability in NumPy code.


Broadcasting is a fundamental concept in NumPy that plays a crucial role in efficient and concise array operations. Its importance lies in several aspects:

1. **Efficiency**: Broadcasting eliminates the need for explicit loops and enables element-wise operations on arrays of different shapes. This leads to faster execution and improved performance, especially when working with large arrays.

2. **Memory Conservation**: By avoiding the creation of intermediate arrays, broadcasting reduces memory usage and overhead. This is particularly beneficial when dealing with large datasets or when memory resources are limited.

3. **Concise and Readable Code**: Broadcasting allows you to express array operations in a more concise and intuitive manner. It eliminates the need for manual reshaping or explicit loops, resulting in cleaner and more readable code.

4. **Flexibility**: Broadcasting enables you to perform operations on arrays with different shapes seamlessly. It provides a flexible and powerful way to combine and manipulate arrays, making it easier to work with complex data structures.

5. **Reusability**: By leveraging broadcasting in user-defined functions, you can create more versatile and reusable code. Functions designed with broadcasting in mind can handle inputs of different shapes, making them more generic and applicable to a wider range of scenarios.


Understanding and effectively utilizing broadcasting is essential for any NumPy user. It empowers you to write efficient, concise, and flexible code, making your data manipulation and numerical computations more streamlined and productive.


As you continue to work with NumPy and explore its vast ecosystem, keep the concept of broadcasting in mind. Embrace its power, but also be aware of its limitations and potential pitfalls. With practice and experience, broadcasting will become a natural and indispensable tool in your NumPy toolkit.


So, go forth and harness the power of broadcasting in your NumPy projects, and enjoy the benefits of efficient and expressive array operations!

<img src="../images/exercise-banner.gif" width="800">

## <a id='toc6_'></a>[Practice Exercise: Broadcasting in NumPy](#toc0_)

In this exercise, you will apply your knowledge of broadcasting to perform various array operations using NumPy.

1. Create a 2D NumPy array `arr1` with shape `(3, 4)` filled with random integers between 1 and 10 (inclusive).

2. Create a 1D NumPy array `arr2` with shape `(4,)` filled with the values `[2, 4, 6, 8]`.

3. Perform element-wise addition between `arr1` and `arr2` using broadcasting and store the result in a new array `result1`.

4. Create a 2D NumPy array `arr3` with shape `(3, 1)` filled with the values `[10, 20, 30]`.

5. Perform element-wise multiplication between `arr1` and `arr3` using broadcasting and store the result in a new array `result2`.

6. Create a scalar value `scalar` with the value 5.

7. Subtract `scalar` from each element of `result1` using broadcasting and store the result in a new array `result3`.

8. Print the arrays `result1`, `result2`, and `result3`.


### <a id='toc6_1_'></a>[Solution](#toc0_)


Here's the solution to the practice exercise:


In [32]:
import numpy as np

In [33]:
# 1. Create arr1 with shape (3, 4) filled with random integers between 1 and 10
arr1 = np.random.randint(1, 11, size=(3, 4))
print("arr1:")
print(arr1)

arr1:
[[7 4 3 6]
 [4 2 1 5]
 [8 3 8 3]]


In [34]:
# 2. Create arr2 with shape (4,) filled with the values [2, 4, 6, 8]
arr2 = np.array([2, 4, 6, 8])
print("\narr2:")
print(arr2)


arr2:
[2 4 6 8]


In [35]:
# 3. Perform element-wise addition between arr1 and arr2 using broadcasting
result1 = arr1 + arr2
print("\nresult1:")
print(result1)


result1:
[[ 9  8  9 14]
 [ 6  6  7 13]
 [10  7 14 11]]


In [36]:
# 4. Create arr3 with shape (3, 1) filled with the values [10, 20, 30]
arr3 = np.array([[10], [20], [30]])
print("\narr3:")
print(arr3)


arr3:
[[10]
 [20]
 [30]]


In [37]:
# 5. Perform element-wise multiplication between arr1 and arr3 using broadcasting
result2 = arr1 * arr3
print("\nresult2:")
print(result2)


result2:
[[ 70  40  30  60]
 [ 80  40  20 100]
 [240  90 240  90]]


In [38]:
# 6. Create a scalar value scalar with the value 5
scalar = 5

In [39]:
# 7. Subtract scalar from each element of result1 using broadcasting
result3 = result1 - scalar
print("\nresult3:")
print(result3)


result3:
[[4 3 4 9]
 [1 1 2 8]
 [5 2 9 6]]


In this solution, we create the arrays `arr1`, `arr2`, and `arr3` according to the instructions. We then perform the specified broadcasting operations to obtain `result1`, `result2`, and `result3`. Finally, we print the resulting arrays.


This exercise helps you practice applying broadcasting rules to perform element-wise operations between arrays of different shapes and between arrays and scalars.